// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChannelMessage struct {
	_tab flatbuffers.Table
}

func GetRootAsChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChannelMessage{}
	x.Init(buf, n+offset)
	return x
}

func FinishChannelMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsChannelMessage(buf []byte, offset flatbuffers.UOffsetT) *ChannelMessage {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ChannelMessage{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedChannelMessageBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ChannelMessage) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChannelMessage) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChannelMessage) ClanId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateClanId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *ChannelMessage) ChannelId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateChannelId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ChannelMessage) MessageId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateMessageId(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *ChannelMessage) Code() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateCode(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *ChannelMessage) SenderId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateSenderId(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *ChannelMessage) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) Avatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) Content() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) ChannelLabel() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) ClanLogo() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) CategoryName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) DisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) ClanNick() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) ClanAvatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) Reactions(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChannelMessage) ReactionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessage) ReactionsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) MutateReactions(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ChannelMessage) Mentions(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChannelMessage) MentionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessage) MentionsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) MutateMentions(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ChannelMessage) Attachments(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChannelMessage) AttachmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessage) AttachmentsBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) MutateAttachments(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ChannelMessage) References(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChannelMessage) ReferencesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessage) ReferencesBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) MutateReferences(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ChannelMessage) ReferencedMessage(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ChannelMessage) ReferencedMessageLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ChannelMessage) ReferencedMessageBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ChannelMessage) MutateReferencedMessage(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ChannelMessage) CreateTimeSeconds() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateCreateTimeSeconds(n uint32) bool {
	return rcv._tab.MutateUint32Slot(42, n)
}

func (rcv *ChannelMessage) UpdateTimeSeconds() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateUpdateTimeSeconds(n uint32) bool {
	return rcv._tab.MutateUint32Slot(44, n)
}

func (rcv *ChannelMessage) Mode() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateMode(n int32) bool {
	return rcv._tab.MutateInt32Slot(46, n)
}

func (rcv *ChannelMessage) HideEditted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ChannelMessage) MutateHideEditted(n bool) bool {
	return rcv._tab.MutateBoolSlot(48, n)
}

func (rcv *ChannelMessage) IsPublic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(50))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ChannelMessage) MutateIsPublic(n bool) bool {
	return rcv._tab.MutateBoolSlot(50, n)
}

func (rcv *ChannelMessage) TopicId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(52))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ChannelMessage) MutateTopicId(n int64) bool {
	return rcv._tab.MutateInt64Slot(52, n)
}

func ChannelMessageStart(builder *flatbuffers.Builder) {
	builder.StartObject(25)
}
func ChannelMessageAddClanId(builder *flatbuffers.Builder, clanId int64) {
	builder.PrependInt64Slot(0, clanId, 0)
}
func ChannelMessageAddChannelId(builder *flatbuffers.Builder, channelId int64) {
	builder.PrependInt64Slot(1, channelId, 0)
}
func ChannelMessageAddMessageId(builder *flatbuffers.Builder, messageId int64) {
	builder.PrependInt64Slot(2, messageId, 0)
}
func ChannelMessageAddCode(builder *flatbuffers.Builder, code int32) {
	builder.PrependInt32Slot(3, code, 0)
}
func ChannelMessageAddSenderId(builder *flatbuffers.Builder, senderId int64) {
	builder.PrependInt64Slot(4, senderId, 0)
}
func ChannelMessageAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(username), 0)
}
func ChannelMessageAddAvatar(builder *flatbuffers.Builder, avatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(avatar), 0)
}
func ChannelMessageAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(content), 0)
}
func ChannelMessageAddChannelLabel(builder *flatbuffers.Builder, channelLabel flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(channelLabel), 0)
}
func ChannelMessageAddClanLogo(builder *flatbuffers.Builder, clanLogo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(clanLogo), 0)
}
func ChannelMessageAddCategoryName(builder *flatbuffers.Builder, categoryName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(categoryName), 0)
}
func ChannelMessageAddDisplayName(builder *flatbuffers.Builder, displayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(displayName), 0)
}
func ChannelMessageAddClanNick(builder *flatbuffers.Builder, clanNick flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(clanNick), 0)
}
func ChannelMessageAddClanAvatar(builder *flatbuffers.Builder, clanAvatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(clanAvatar), 0)
}
func ChannelMessageAddReactions(builder *flatbuffers.Builder, reactions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(reactions), 0)
}
func ChannelMessageStartReactionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChannelMessageAddMentions(builder *flatbuffers.Builder, mentions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(mentions), 0)
}
func ChannelMessageStartMentionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChannelMessageAddAttachments(builder *flatbuffers.Builder, attachments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(attachments), 0)
}
func ChannelMessageStartAttachmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChannelMessageAddReferences(builder *flatbuffers.Builder, references flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(references), 0)
}
func ChannelMessageStartReferencesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChannelMessageAddReferencedMessage(builder *flatbuffers.Builder, referencedMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(referencedMessage), 0)
}
func ChannelMessageStartReferencedMessageVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ChannelMessageAddCreateTimeSeconds(builder *flatbuffers.Builder, createTimeSeconds uint32) {
	builder.PrependUint32Slot(19, createTimeSeconds, 0)
}
func ChannelMessageAddUpdateTimeSeconds(builder *flatbuffers.Builder, updateTimeSeconds uint32) {
	builder.PrependUint32Slot(20, updateTimeSeconds, 0)
}
func ChannelMessageAddMode(builder *flatbuffers.Builder, mode int32) {
	builder.PrependInt32Slot(21, mode, 0)
}
func ChannelMessageAddHideEditted(builder *flatbuffers.Builder, hideEditted bool) {
	builder.PrependBoolSlot(22, hideEditted, false)
}
func ChannelMessageAddIsPublic(builder *flatbuffers.Builder, isPublic bool) {
	builder.PrependBoolSlot(23, isPublic, false)
}
func ChannelMessageAddTopicId(builder *flatbuffers.Builder, topicId int64) {
	builder.PrependInt64Slot(24, topicId, 0)
}
func ChannelMessageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type MessageMention struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageMention(buf []byte, offset flatbuffers.UOffsetT) *MessageMention {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageMention{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageMentionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageMention(buf []byte, offset flatbuffers.UOffsetT) *MessageMention {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageMention{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageMentionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageMention) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageMention) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageMention) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *MessageMention) UserId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateUserId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *MessageMention) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageMention) RoleId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateRoleId(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *MessageMention) Rolename() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageMention) CreateTimeSeconds() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateCreateTimeSeconds(n uint32) bool {
	return rcv._tab.MutateUint32Slot(14, n)
}

func (rcv *MessageMention) S() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateS(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *MessageMention) E() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageMention) MutateE(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func MessageMentionStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func MessageMentionAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func MessageMentionAddUserId(builder *flatbuffers.Builder, userId int64) {
	builder.PrependInt64Slot(1, userId, 0)
}
func MessageMentionAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(username), 0)
}
func MessageMentionAddRoleId(builder *flatbuffers.Builder, roleId int64) {
	builder.PrependInt64Slot(3, roleId, 0)
}
func MessageMentionAddRolename(builder *flatbuffers.Builder, rolename flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(rolename), 0)
}
func MessageMentionAddCreateTimeSeconds(builder *flatbuffers.Builder, createTimeSeconds uint32) {
	builder.PrependUint32Slot(5, createTimeSeconds, 0)
}
func MessageMentionAddS(builder *flatbuffers.Builder, s int32) {
	builder.PrependInt32Slot(6, s, 0)
}
func MessageMentionAddE(builder *flatbuffers.Builder, e int32) {
	builder.PrependInt32Slot(7, e, 0)
}
func MessageMentionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type MessageAttachment struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageAttachment(buf []byte, offset flatbuffers.UOffsetT) *MessageAttachment {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageAttachment{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageAttachmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageAttachment(buf []byte, offset flatbuffers.UOffsetT) *MessageAttachment {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageAttachment{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageAttachmentBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageAttachment) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageAttachment) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageAttachment) Filename() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageAttachment) Size() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageAttachment) MutateSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *MessageAttachment) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageAttachment) Filetype() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageAttachment) Width() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageAttachment) MutateWidth(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *MessageAttachment) Height() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageAttachment) MutateHeight(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *MessageAttachment) Thumbnail() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageAttachment) Duration() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageAttachment) MutateDuration(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func MessageAttachmentStart(builder *flatbuffers.Builder) {
	builder.StartObject(8)
}
func MessageAttachmentAddFilename(builder *flatbuffers.Builder, filename flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(filename), 0)
}
func MessageAttachmentAddSize(builder *flatbuffers.Builder, size int32) {
	builder.PrependInt32Slot(1, size, 0)
}
func MessageAttachmentAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(url), 0)
}
func MessageAttachmentAddFiletype(builder *flatbuffers.Builder, filetype flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(filetype), 0)
}
func MessageAttachmentAddWidth(builder *flatbuffers.Builder, width int32) {
	builder.PrependInt32Slot(4, width, 0)
}
func MessageAttachmentAddHeight(builder *flatbuffers.Builder, height int32) {
	builder.PrependInt32Slot(5, height, 0)
}
func MessageAttachmentAddThumbnail(builder *flatbuffers.Builder, thumbnail flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(thumbnail), 0)
}
func MessageAttachmentAddDuration(builder *flatbuffers.Builder, duration int32) {
	builder.PrependInt32Slot(7, duration, 0)
}
func MessageAttachmentEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type MessageRef struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageRef(buf []byte, offset flatbuffers.UOffsetT) *MessageRef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageRef{}
	x.Init(buf, n+offset)
	return x
}

func FinishMessageRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMessageRef(buf []byte, offset flatbuffers.UOffsetT) *MessageRef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageRef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMessageRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MessageRef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageRef) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageRef) MessageId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageRef) MutateMessageId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *MessageRef) MessageRefId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageRef) MutateMessageRefId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *MessageRef) Content() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageRef) HasAttachment() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MessageRef) MutateHasAttachment(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *MessageRef) RefType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageRef) MutateRefType(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *MessageRef) MessageSenderId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MessageRef) MutateMessageSenderId(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *MessageRef) MessageSenderUsername() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageRef) MesagesSenderAvatar() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageRef) MessageSenderClanNick() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageRef) MessageSenderDisplayName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MessageRefStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func MessageRefAddMessageId(builder *flatbuffers.Builder, messageId int64) {
	builder.PrependInt64Slot(0, messageId, 0)
}
func MessageRefAddMessageRefId(builder *flatbuffers.Builder, messageRefId int64) {
	builder.PrependInt64Slot(1, messageRefId, 0)
}
func MessageRefAddContent(builder *flatbuffers.Builder, content flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(content), 0)
}
func MessageRefAddHasAttachment(builder *flatbuffers.Builder, hasAttachment bool) {
	builder.PrependBoolSlot(3, hasAttachment, false)
}
func MessageRefAddRefType(builder *flatbuffers.Builder, refType int32) {
	builder.PrependInt32Slot(4, refType, 0)
}
func MessageRefAddMessageSenderId(builder *flatbuffers.Builder, messageSenderId int64) {
	builder.PrependInt64Slot(5, messageSenderId, 0)
}
func MessageRefAddMessageSenderUsername(builder *flatbuffers.Builder, messageSenderUsername flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(messageSenderUsername), 0)
}
func MessageRefAddMesagesSenderAvatar(builder *flatbuffers.Builder, mesagesSenderAvatar flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(mesagesSenderAvatar), 0)
}
func MessageRefAddMessageSenderClanNick(builder *flatbuffers.Builder, messageSenderClanNick flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(messageSenderClanNick), 0)
}
func MessageRefAddMessageSenderDisplayName(builder *flatbuffers.Builder, messageSenderDisplayName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(messageSenderDisplayName), 0)
}
func MessageRefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type FcmDataPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsFcmDataPayload(buf []byte, offset flatbuffers.UOffsetT) *FcmDataPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FcmDataPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishFcmDataPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFcmDataPayload(buf []byte, offset flatbuffers.UOffsetT) *FcmDataPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FcmDataPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFcmDataPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FcmDataPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FcmDataPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FcmDataPayload) CommandType() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FcmDataPayload) MutateCommandType(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *FcmDataPayload) ReceiverId() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FcmDataPayload) MutateReceiverId(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *FcmDataPayload) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FcmDataPayload) Body(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *FcmDataPayload) BodyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FcmDataPayload) BodyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FcmDataPayload) MutateBody(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *FcmDataPayload) UserRoleIds(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *FcmDataPayload) UserRoleIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FcmDataPayload) MutateUserRoleIds(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *FcmDataPayload) UserSentIds(j int) int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt64(a + flatbuffers.UOffsetT(j*8))
	}
	return 0
}

func (rcv *FcmDataPayload) UserSentIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FcmDataPayload) MutateUserSentIds(j int, n int64) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt64(a+flatbuffers.UOffsetT(j*8), n)
	}
	return false
}

func (rcv *FcmDataPayload) Priority() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FcmDataPayload) MutatePriority(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *FcmDataPayload) Message(obj *ChannelMessage) *ChannelMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ChannelMessage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *FcmDataPayload) IsE2ee() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FcmDataPayload) MutateIsE2ee(n bool) bool {
	return rcv._tab.MutateBoolSlot(20, n)
}

func (rcv *FcmDataPayload) IsDm() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FcmDataPayload) MutateIsDm(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *FcmDataPayload) MentionHere() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FcmDataPayload) MutateMentionHere(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func (rcv *FcmDataPayload) Mentions(obj *MessageMention, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FcmDataPayload) MentionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FcmDataPayload) References(obj *MessageRef, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FcmDataPayload) ReferencesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *FcmDataPayload) Attachments(obj *MessageAttachment, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *FcmDataPayload) AttachmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func FcmDataPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(14)
}
func FcmDataPayloadAddCommandType(builder *flatbuffers.Builder, commandType int32) {
	builder.PrependInt32Slot(0, commandType, 0)
}
func FcmDataPayloadAddReceiverId(builder *flatbuffers.Builder, receiverId int64) {
	builder.PrependInt64Slot(1, receiverId, 0)
}
func FcmDataPayloadAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(title), 0)
}
func FcmDataPayloadAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(body), 0)
}
func FcmDataPayloadStartBodyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func FcmDataPayloadAddUserRoleIds(builder *flatbuffers.Builder, userRoleIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(userRoleIds), 0)
}
func FcmDataPayloadStartUserRoleIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func FcmDataPayloadAddUserSentIds(builder *flatbuffers.Builder, userSentIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(userSentIds), 0)
}
func FcmDataPayloadStartUserSentIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(8, numElems, 8)
}
func FcmDataPayloadAddPriority(builder *flatbuffers.Builder, priority int32) {
	builder.PrependInt32Slot(6, priority, 0)
}
func FcmDataPayloadAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(message), 0)
}
func FcmDataPayloadAddIsE2ee(builder *flatbuffers.Builder, isE2ee bool) {
	builder.PrependBoolSlot(8, isE2ee, false)
}
func FcmDataPayloadAddIsDm(builder *flatbuffers.Builder, isDm bool) {
	builder.PrependBoolSlot(9, isDm, false)
}
func FcmDataPayloadAddMentionHere(builder *flatbuffers.Builder, mentionHere bool) {
	builder.PrependBoolSlot(10, mentionHere, false)
}
func FcmDataPayloadAddMentions(builder *flatbuffers.Builder, mentions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(mentions), 0)
}
func FcmDataPayloadStartMentionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FcmDataPayloadAddReferences(builder *flatbuffers.Builder, references flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(references), 0)
}
func FcmDataPayloadStartReferencesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FcmDataPayloadAddAttachments(builder *flatbuffers.Builder, attachments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(attachments), 0)
}
func FcmDataPayloadStartAttachmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FcmDataPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
